// Mocks generated by Mockito 5.4.6 from annotations
// in doctorak/test/features/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doctorak/core/shared/models/doctors_response_model.dart' as _i3;
import 'package:doctorak/features/home/data/data_source/home_remote_data_source.dart'
    as _i4;
import 'package:doctorak/features/home/data/models/specializations_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSpecializationsResponseModel_0 extends _i1.SmartFake
    implements _i2.SpecializationsResponseModel {
  _FakeSpecializationsResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeDoctorsResponseModel_1 extends _i1.SmartFake
    implements _i3.DoctorsResponseModel {
  _FakeDoctorsResponseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseHomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseHomeRemoteDataSource extends _i1.Mock
    implements _i4.BaseHomeRemoteDataSource {
  MockBaseHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SpecializationsResponseModel> getHomeSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeSpecializations, []),
            returnValue: _i5.Future<_i2.SpecializationsResponseModel>.value(
              _FakeSpecializationsResponseModel_0(
                this,
                Invocation.method(#getHomeSpecializations, []),
              ),
            ),
          )
          as _i5.Future<_i2.SpecializationsResponseModel>);

  @override
  _i5.Future<_i2.SpecializationsResponseModel> getAllSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSpecializations, []),
            returnValue: _i5.Future<_i2.SpecializationsResponseModel>.value(
              _FakeSpecializationsResponseModel_0(
                this,
                Invocation.method(#getAllSpecializations, []),
              ),
            ),
          )
          as _i5.Future<_i2.SpecializationsResponseModel>);

  @override
  _i5.Future<_i3.DoctorsResponseModel> getAllDoctors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDoctors, []),
            returnValue: _i5.Future<_i3.DoctorsResponseModel>.value(
              _FakeDoctorsResponseModel_1(
                this,
                Invocation.method(#getAllDoctors, []),
              ),
            ),
          )
          as _i5.Future<_i3.DoctorsResponseModel>);
}
