// Mocks generated by Mockito 5.4.6 from annotations
// in doctorak/test/features/appointments/presentation/controllers/book_appointment_cubit/book_appointment_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doctorak/core/network/api_result.dart' as _i2;
import 'package:doctorak/core/services/notification_service.dart' as _i10;
import 'package:doctorak/core/services/payment_data.dart' as _i9;
import 'package:doctorak/features/appointments/domain/entities/appointment_entity.dart'
    as _i6;
import 'package:doctorak/features/appointments/domain/entities/book_appointment_request_entity.dart'
    as _i7;
import 'package:doctorak/features/appointments/domain/repositories/base_appointments_repository.dart'
    as _i4;
import 'package:doctorak/features/appointments/domain/repositories/base_payment_repository.dart'
    as _i8;
import 'package:doctorak/features/notifications/presentation/controllers/notifications_cubit/notifications_cubit.dart'
    as _i11;
import 'package:doctorak/features/notifications/presentation/controllers/notifications_cubit/notifications_state.dart'
    as _i3;
import 'package:hydrated_bloc/hydrated_bloc.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationsState_1 extends _i1.SmartFake
    implements _i3.NotificationsState {
  _FakeNotificationsState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseAppointmentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseAppointmentsRepository extends _i1.Mock
    implements _i4.BaseAppointmentsRepository {
  MockBaseAppointmentsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResult<_i6.AppointmentEntity>> bookAppointment(
    _i7.BookAppointmentRequestEntity? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bookAppointment, [request]),
            returnValue: _i5.Future<_i2.ApiResult<_i6.AppointmentEntity>>.value(
              _FakeApiResult_0<_i6.AppointmentEntity>(
                this,
                Invocation.method(#bookAppointment, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<_i6.AppointmentEntity>>);

  @override
  _i5.Future<_i2.ApiResult<List<_i6.AppointmentEntity>>> getMyAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getMyAppointments, []),
            returnValue:
                _i5.Future<_i2.ApiResult<List<_i6.AppointmentEntity>>>.value(
                  _FakeApiResult_0<List<_i6.AppointmentEntity>>(
                    this,
                    Invocation.method(#getMyAppointments, []),
                  ),
                ),
          )
          as _i5.Future<_i2.ApiResult<List<_i6.AppointmentEntity>>>);
}

/// A class which mocks [BasePaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasePaymentRepository extends _i1.Mock
    implements _i8.BasePaymentRepository {
  MockBasePaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResult<void>> processStripePayment(
    _i9.PaymentData? paymentData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processStripePayment, [paymentData]),
            returnValue: _i5.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#processStripePayment, [paymentData]),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i10.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> showBookingConfirmation(
    _i6.AppointmentEntity? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#showBookingConfirmation, [appointment]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> scheduleAppointmentReminder(
    _i6.AppointmentEntity? appointment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAppointmentReminder, [appointment]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelReminder(int? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelReminder, [appointmentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll(int? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, [appointmentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NotificationsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsCubit extends _i1.Mock
    implements _i11.NotificationsCubit {
  MockNotificationsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.NotificationsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNotificationsState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.NotificationsState);

  @override
  _i5.Stream<_i3.NotificationsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.NotificationsState>.empty(),
          )
          as _i5.Stream<_i3.NotificationsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  String get storagePrefix =>
      (super.noSuchMethod(
            Invocation.getter(#storagePrefix),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#storagePrefix),
            ),
          )
          as String);

  @override
  String get storageToken =>
      (super.noSuchMethod(
            Invocation.getter(#storageToken),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#storageToken),
            ),
          )
          as String);

  @override
  void addBookingConfirmation(_i6.AppointmentEntity? appointment) =>
      super.noSuchMethod(
        Invocation.method(#addBookingConfirmation, [appointment]),
        returnValueForMissingStub: null,
      );

  @override
  void addAppointmentReminder(_i6.AppointmentEntity? appointment) =>
      super.noSuchMethod(
        Invocation.method(#addAppointmentReminder, [appointment]),
        returnValueForMissingStub: null,
      );

  @override
  void markAsRead(String? notificationId) => super.noSuchMethod(
    Invocation.method(#markAsRead, [notificationId]),
    returnValueForMissingStub: null,
  );

  @override
  void markAllAsRead() => super.noSuchMethod(
    Invocation.method(#markAllAsRead, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.NotificationsState? fromJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(Invocation.method(#fromJson, [json]))
          as _i3.NotificationsState?);

  @override
  Map<String, dynamic>? toJson(_i3.NotificationsState? state) =>
      (super.noSuchMethod(Invocation.method(#toJson, [state]))
          as Map<String, dynamic>?);

  @override
  void emit(_i3.NotificationsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i13.Change<_i3.NotificationsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void hydrate({
    _i13.Storage? storage,
    _i13.OnHydrationError? onError = _i13.defaultOnHydrationError,
  }) => super.noSuchMethod(
    Invocation.method(#hydrate, [], {#storage: storage, #onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
