
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    Dir.chdir("..") do
      sh "flutter clean"
      sh "flutter build apk --release --target lib/main_production.dart"
    end
    firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "testers",
        release_notes: "First Fastlane Firebase Distribution",
        debug: true
  )
  end
end