// Mocks generated by Mockito 5.4.6 from annotations
// in doctorak/test/features/home/presentation/controller/all_doctors_cubit/all_doctors_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:doctorak/core/network/api_result.dart' as _i2;
import 'package:doctorak/core/shared/entities/doctors_response_entity.dart'
    as _i6;
import 'package:doctorak/features/home/domain/entities/specializations_response_entity.dart'
    as _i5;
import 'package:doctorak/features/home/domain/repositories/base_home_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BaseHomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseHomeRepository extends _i1.Mock
    implements _i3.BaseHomeRepository {
  MockBaseHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.SpecializationsResponseEntity>>
  getHomeSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeSpecializations, []),
            returnValue:
                _i4.Future<
                  _i2.ApiResult<_i5.SpecializationsResponseEntity>
                >.value(
                  _FakeApiResult_0<_i5.SpecializationsResponseEntity>(
                    this,
                    Invocation.method(#getHomeSpecializations, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResult<_i5.SpecializationsResponseEntity>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.SpecializationsResponseEntity>>
  getAllSpecializations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSpecializations, []),
            returnValue:
                _i4.Future<
                  _i2.ApiResult<_i5.SpecializationsResponseEntity>
                >.value(
                  _FakeApiResult_0<_i5.SpecializationsResponseEntity>(
                    this,
                    Invocation.method(#getAllSpecializations, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResult<_i5.SpecializationsResponseEntity>>);

  @override
  _i4.Future<_i2.ApiResult<_i6.DoctorsResponseEntity>> getAllDoctors() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDoctors, []),
            returnValue:
                _i4.Future<_i2.ApiResult<_i6.DoctorsResponseEntity>>.value(
                  _FakeApiResult_0<_i6.DoctorsResponseEntity>(
                    this,
                    Invocation.method(#getAllDoctors, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResult<_i6.DoctorsResponseEntity>>);
}
